baseURL = "https://microp11.github.io/"
languageCode = "en-us"
title = "A sea kayak story"
description = "A sea kayak story"
theme = "min_night"

disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]
pluralizelisttitles = "false"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Paul Maxan"
    description = "A sea kayak story"
    logo = ""
    twitterAuthor = "@microp11sat"
    githubUsername = "microp11"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atelier-lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]
    noreadingtime = true

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/planning/"
    name = "Planning"
    weight = 2


[[menu.main]]
    url = "/dry-run/"
    name = "Dry-run"
    weight = 3

[[menu.main]]
    url = "/trip/"
    name = "Trip"
    weight = 4

[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:pmaxan@yahoo.com"
    name = "far fa-envelope"
    weight = 1

# [[menu.icon]]
#     url = "https://github.com/microp11"
#     name = "fab fa-github"
#     weight = 2

# [[menu.icon]]
#     url = "https://bitbucket.org/scytalec/"
#     name = "fab fa-bitbucket"
#     weight = 3

[[menu.icon]]
    url = "https://twitter.com/microp11sat/"
    name = "fab fa-twitter"
    weight = 4

[[menu.icon]]
    url = "https://www.facebook.com/pmaxan/"
    name = "fab fa-facebook"
    weight = 5

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/paul-maxan-44b41346/"
#     name = "fab fa-linkedin"
#     weight = 6

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/users/5878751/nate"
#    name = "fab fa-stack-overflow"
#   weight = 5
